# Generated by Django 3.0.5 on 2020-04-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200424_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(default='images/users/default/brand.png', upload_to='users/%Y/%m'),
        ),
    ]
