# Generated by Django 3.0.7 on 2020-07-21 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesystem',
            name='guard',
        ),
    ]
