# Generated by Django 3.0.7 on 2020-06-18 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemsite', '0002_auto_20200618_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesystem',
            old_name='guard',
            new_name='guards',
        ),
    ]
