# Generated by Django 3.0.7 on 2020-06-18 17:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('systemsite', '0003_auto_20200618_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'places',
            },
        ),
        migrations.AddField(
            model_name='sitesystem',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesystem',
            name='start_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sitesystem',
            name='guards',
            field=models.ManyToManyField(related_name='guards', to=settings.AUTH_USER_MODEL),
        ),
    ]
