# Generated by Django 3.0.7 on 2020-06-18 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemsite', '0005_sitesystem_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesystem',
            old_name='site',
            new_name='place',
        ),
    ]
