# Generated by Django 3.0.7 on 2020-06-20 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemsite', '0006_auto_20200618_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesystem',
            name='guards',
        ),
        migrations.AlterField(
            model_name='sitesystem',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sitesystem',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemsite.Place'),
        ),
    ]
