# Generated by Django 3.0.7 on 2020-06-20 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weapon', '0001_initial'),
        ('systemsite', '0007_auto_20200620_2105'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField()),
                ('sites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemsite.SiteSystem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('weapons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weapon.Weapon')),
            ],
        ),
    ]
