# Generated by Django 3.0.7 on 2020-06-21 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='sites',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='weapons',
            new_name='weapon',
        ),
    ]
